repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: billimek
    url: https://billimek.com/billimek-charts/
  - name: loki
    url: https://grafana.github.io/loki/charts
  - name: halkeye
    url: https://halkeye.github.io/helm-charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: kong
    url: https://charts.konghq.com
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
  - name: szymonrychu
    url: https://raw.githubusercontent.com/szymonrychu/charts/master/

templates:
  default: &default
    missingFileHandler: Warn
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args: [ "./scripts/post.sh", "{{`{{ .Release.Name }}`}}"]
      - events: ["prepare"]
        showlogs: true
        command: "bash"
        args: [ "./scripts/pre.sh", "{{`{{ .Release.Name }}`}}"]
    values:
      - values/{{`{{ .Release.Name }}`}}/values.yaml
      - values/{{`{{ .Release.Name }}`}}/values.secrets.yaml

releases:
  - name: kong
    chart: kong/kong
    namespace: kube-system
    version: "1.9.*"
    <<: *default

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: kube-system
    version: "1.2.*"
    <<: *default

  - name: ovh-dns-updater
    chart: szymonrychu/ovh-dns-updater
    version: 1.0.0
    namespace: kube-system
    <<: *default

  - name: metallb
    chart: bitnami/metallb
    namespace: kube-system
    version: "2.0.4" # latest release without 'common' bitnami chart in dependencies
    <<: *default

  - name: keycloak
    timeout: 600
    version: 10.1.0
    chart: codecentric/keycloak
    namespace: keycloak
    <<: *default

  - name: prometheus-operator
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "13.13.*"
    force: true
    # passes --disable-validation to helm 3 diff plugin, this requires diff plugin >= 3.1.2 It may be helpful to deploy charts with helm api v1 CRDS
    disableValidation: true
    # passes --disable-validation to helm 3 diff plugin, this requires diff plugin >= 3.1.2 It may be helpful to deploy charts with helm api v1 CRDS
    disableValidationOnInstall: true
    <<: *default

  - name: loki
    chart: loki/loki-stack
    version: 0.37.3
    namespace: monitoring
    <<: *default

  - name: emby
    chart: ./charts/emby
    namespace: emby
    <<: *default

  - name: rtorrent
    chart: billimek/rtorrent-flood
    version: "4.1.*"
    namespace: rtorrent
    <<: *default

  - name: plant-watering-server
    chart: szymonrychu/plant-manager
    version: 1.0.0
    namespace: plant-manager
    <<: *default
