repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: billimek
    url: https://billimek.com/billimek-charts/
  - name: loki
    url: https://grafana.github.io/loki/charts
  - name: halkeye
    url: https://halkeye.github.io/helm-charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

templates:
  default: &default
    missingFileHandler: Warn
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "bash"
        args: [ "./scripts/post.sh", "{{`{{ .Release.Name }}`}}"]
      - events: ["prepare"]
        showlogs: true
        command: "bash"
        args: [ "./scripts/pre.sh", "{{`{{ .Release.Name }}`}}"]
    values:
      - values/{{`{{ .Release.Name }}`}}/values.yaml
      - values/{{`{{ .Release.Name }}`}}/values.secrets.yaml

releases:
  - name: kong
    chart: kong/kong
    namespace: kube-system
    version: "1.9.*"
    <<: *default

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: kube-system
    version: "0.15.*"
    <<: *default

  - name: metallb
    chart: stable/metallb
    namespace: kube-system
    version: "0.12.*"
    <<: *default

  - name: emby
    chart: ./charts/emby
    namespace: emby
    <<: *default

  - name: ovh-dns-updater
    chart: ./charts/ovh-dns-updater
    namespace: kube-system
    <<: *default

  - name: rtorrent
    chart: billimek/rtorrent-flood
    version: "4.1.*"
    namespace: rtorrent
    <<: *default

  # - name: nextcloud
  #   chart: stable/nextcloud
  #   version: "1.12.*"
  #   namespace: nextcloud
  #   <<: *default

  - name: keycloak
    timeout: 600
    version: "9.0.*"
    chart: codecentric/keycloak
    namespace: keycloak
    <<: *default

  # - name: octoprint
  #   chart: halkeye/octoprint
  #   version: 0.1.1
  #   namespace: octoprint
  #   <<: *default

  - name: prometheus
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: "9.3.*"
    <<: *default

  - name: loki
    chart: loki/loki-stack
    version: 0.37.3
    namespace: monitoring
    <<: *default
