repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com/incubator
  - name: jetstack
    url: https://charts.jetstack.io
  - name: billimek
    url: https://billimek.com/billimek-charts/
  - name: loki
    url: https://grafana.github.io/loki/charts
  - name: halkeye
    url: https://halkeye.github.io/helm-charts/

templates:
  default: &default
    missingFileHandler: Warn
    values:
      - helm/{{`{{ .Release.Name }}`}}/values.yaml
    secrets:
      - helm/{{`{{ .Release.Name }}`}}/values.secrets.yaml

releases:
  - name: ingress
    chart: stable/nginx-ingress
    namespace: kube-system
    version: 1.39.0
    <<: *default

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: kube-system
    version: 0.15.1
    <<: *default

  - name: metallb
    chart: stable/metallb
    namespace: kube-system
    version: 0.12.0
    <<: *default

  - name: prometheus
    chart: stable/prometheus-operator
    namespace: monitoring
    version: 8.13.12
    <<: *default

  - name: emby
    chart: ./emby
    namespace: emby
    <<: *default

  - name: ovh-dns-updater
    chart: ./baremetal_external_dns/ovh-dns-updater
    namespace: kube-system
    <<: *default

  - name: rtorrent
    chart: billimek/rtorrent-flood
    version: 4.1.1
    namespace: rtorrent
    <<: *default

  # - name: octoprint
  #   chart: halkeye/octoprint
  #   version: 0.1.1
  #   namespace: octoprint
  #   <<: *default

  - name: loki
    chart: loki/loki-stack
    version: 0.37.3
    namespace: loki
    <<: *default

