
ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  hosts:
    - emby.szymonrichert.pl
  tls:
   - secretName: emby-tls
     hosts:
       - emby.szymonrichert.pl

volumes:
  - name: emby-local-pvc
    persistentVolumeClaim:
      claimName: emby-local-pvc

volumeMounts:
  - name: emby-local-pvc
    mountPath: "/config"
    subPath: "configs"
  - name: emby-local-pvc
    mountPath: "/medias"
    subPath: "medias"