
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "kong"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: emby.szymonrichert.pl
      paths: 
        - /
  tls:
    - secretName: emby-tls
      hosts:
        - emby.szymonrichert.pl


additionalVolumes:
  - name: emby-local-pvc
    persistentVolumeClaim:
      claimName: emby-local-pvc

additionalVolumeMounts:
  - name: emby-local-pvc
    mountPath: "/config"
    subPath: "configs"
  - name: emby-local-pvc
    mountPath: "/medias"
    subPath: "medias"