ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - iot.szymonrichert.pl
  path: /
  tls:
    - hosts:
      - iot.szymonrichert.pl
      secretName: tls
