ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: iot.szymonrichert.pl
      paths:
        - /plant-humidity
  tls:
    - secretName: tls
      host: iot.szymonrichert.pl
      
