

basepath: ""

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "kong"
  rules:
    - host: auth.szymonrichert.pl
      paths: 
        - /auth/
  tls:
    - hosts:
        - auth.szymonrichert.pl
      secretName: keycloak-tls

resources:
  requests:
    cpu: "500m"
    memory: "1024Mi"
  limits:
    cpu: "1"
    memory: "2048Mi"

postgresql:
  persistence:
    storageClass: keycloak-local-pv
    accessModes:
      - ReadWriteOnce
    size: 2Gi