---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-local-pv
  labels:
    type: local
spec:
  storageClassName: keycloak-local-pv
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disk/keycloak"
