---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-local-pv
  labels:
    type: local
spec:
  storageClassName: emby-local-pv
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disk/emby"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-local-pvc
  namespace: emby
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: emby-local-pv