device: /dev/ttyACM0

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "kong"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - octoprint.szymonrichert.pl
  path: /
  tls:
    - hosts:
      - octoprint.szymonrichert.pl
      secretName: octoprint-tls
