---
apiVersion: v1
kind: Service
metadata:
  name: octoprint-external
  namespace: octoprint
spec:
  type: ExternalName
  externalName: 192.168.1.30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: octoprint-external
    nginx.ingress.kubernetes.io/auth-realm: 'Octoprint Authentication'
  name: octoprint-external
  namespace: octoprint
spec:
  rules:
  - host: octoprint.szymonrichert.pl
    http:
      paths:
      - backend:
          serviceName: octoprint-external
          servicePort: 5000
        path: /
  tls:
  - hosts:
    - octoprint.szymonrichert.pl
    secretName: octoprint-tls
---
apiVersion: v1
data:
  auth: c3p5bW9ucmk6JDJ5JDEwJE1VMWJBNjRialloNVB1VE1NQ2VIUE92UXo2a0RnVUtsL3NXQmJJendoakZOZEp3VTFzUHZDCg==
kind: Secret
metadata:
  name: octoprint-external
  namespace: octoprint
type: Opaque